version: '3.9'
services:
  app:
    build: 
      args: 
        user: ben
        uid: 1000
      context: ./ 
      dockerfile: Dockerfile 
    container_name: app-setup
    expose:
      - 9000
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./php.ini:/etc/php/7.4/cli/conf.d/php.ini
      - ./:/var/www
    networks:
      - docker-setup
    depends_on:
      - db

  nginx:
    image: nginx:1.21.6-alpine
    container_name: nginx-setup
    restart: unless-stopped
    ports:
      - 9000:80
    volumes:
      - ./default.template.conf:/etc/nginx/conf.d/templates/default.template.conf
      - ./:/var/www
    networks:
      - docker-setup
    depends_on:
      - app
      - db

  db:
    image: mariadb:10.9.3-jammy
    container_name: mysql-setup
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: "${DB_DATABASE:-secret}"
      MYSQL_ROOT_PASSWORD: "${DB_PASSWORD:-secret}"
      MYSQL_PASSWORD: "${DB_PASSWORD:-secret}"
      MYSQL_USER: "${DB_USERNAME:-secret}"
      SERVICE_TAGS: dev
      SERVICE_NAME: mariadb
    ports:
      - 3310:3306
    volumes:
      - setup_data:/var/lib/mysql
    networks:
      - docker-setup
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost", "-u${DB_USERNAME}", "-p${DB_PASSWORD}"]
      retries: 3
      timeout: 5s

networks:
  docker-setup:
    driver: bridge

volumes:
  setup_data:
    driver: local
  
