version: '3.8'
services:
  app:
    build: 
      args: 
        user: ben
        uid: 1000
      context: ./ 
      dockerfile: Dockerfile 
    image: docker-setup
    container_name: app-setup
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - docker-setup

  db:
    image: mysql:8.0
    container_name: mysql-setup
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: "${DB_DATABASE:-secret}"
      MYSQL_ROOT_PASSWORD: "${DB_PASSWORD:-secret}"
      MYSQL_PASSWORD: "${DB_PASSWORD:-secret}"
      MYSQL_USER: "${DB_USERNAME:-secret}"
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    ports:
      - 3310:3306
    volumes:
      - ./conf/mysql:/docker-entrypoint-initdb.d
    networks:
      - docker-setup

  nginx:
    image: nginx:1.17-alpine
    container_name: nginx-setup
    restart: unless-stopped
    ports:
      - 9000:80
    volumes:
      - ./:/var/www
      - ./conf/nginx:/etc/nginx/conf.d
    networks:
      - docker-setup

networks:
  docker-setup:
    driver: bridge
  
